#
#  __  __            _         _        
# |  \/  | __ _ _ __| | ____ _| |_ __ _ 
# | |\/| |/ _` | '__| |/ / _` | __/ _` |
# | |  | | (_| | |  |   < (_| | || (_| |
# |_|  |_|\__,_|_|  |_|\_\__,_|\__\__,_(
#
#                     techstructive-blog

[markata]
# bump site version to bust GitHub actions cache
site_version = 2

# 2 weeks in seconds
default_cache_expire = 1209600

## Markata Setup
glob_patterns = ["blog/posts/*.md", "blog/tils/*.md"]
## glob_patterns = "pages/**/*spaceflights*.md"
output_dir = "markout"
assets_dir = "static"

hooks = [

    # Customized Plugins
    "plugins.feeds",
    "plugins.flat_slug",
    "plugins.tils",
    "plugins.load",
    "plugins.tags",
    "plugins.tag_list",
    "plugins.rss",
    "plugins.gfg_articles",
    "plugins.series",
    "plugins.series_index",

    # Default Plugins
    "markata.cli.cli",
    "markata.cli.header",
    "markata.cli.plugins",
    "markata.cli.runner",
    "markata.cli.server",
    "markata.cli.summary",
    "markata.plugins.auto_title",
    "markata.plugins.base_cli",
    "markata.plugins.copy_assets",
    "markata.plugins.covers",
    "markata.plugins.datetime",
    "markata.plugins.generator",
    "markata.plugins.glob",
    "markata.plugins.icon_resize",
    "markata.plugins.load",
    "markata.plugins.long_description",
    "markata.plugins.post_template",
    "markata.plugins.publish_source",
    "markata.plugins.publish_html",
    "markata.plugins.pyinstrument",
    "markata.plugins.render_markdown",
    "markata.plugins.rss",
    "markata.plugins.sitemap",
    "markata.plugins.to_json",
    "markata.plugins.tui",
    "markata.background",
    "markata.hookspec",
    "markata.lifecycle",
    "markata.errors",
    "markata.standard_config",

#   "plugins.render_template_variables",
#   "plugins.codeblocks",
#   "plugins.index",
#   "plugins.slug",
#   "plugins.one_line_link",
#   "plugins.include",
#   "default",
#   # 'plugins.related',
#   'plugins.seo_amp',
#   'plugins.publish_amp',
#   'plugins.custom_seo',
#   'plugins.gif_to_mp4',
#   'plugins.rss_tag',
#   'plugins.auto_publish',
   ]
disabled_hooks = ['markata.plugins.flat_slug', 'markata.plugins.feeds', 'markata.plugins.rss',]

## Site Config
url = "https://mr-destructive.github.io/techstructive-blog"
title = "Techstructive Blog"
description = "Writing about Vim | Python | Django and Linux"
rss_description = "Techstructive Blog Feed"
author_name = "Meet Gor"
author_email = "gormeet711@gmail.com"
icon = "tbicon.png"
lang = "en"
post_template = "layouts/post_template.html"
amp_template = "layouts/post_template.amp.html"
theme_color = "#00003f"
background_color = "#00003f"
start_url = "/techstructive-blog/"
site_name = "Techstructive Blog"

blog_github_link = "https://github.com/mr-destructive/techstructive-blog/"
blog_branch = "gh-pages"

short_name = "tb"
display = "minimal-ui"
twitter_card = "summary_large_image"
twitter_creator = "@MeetGor21"
twitter_site = "@MeetGor21"

[markata.archive.blog.posts]
template="layouts/archive_template.html"
filter="templateKey in ['blog-post',] and status.lower()=='published'"

[markata.archive.blog.tils]
template="layouts/archive_template.html"
filter="templateKey == 'til'"

[markata.archive]
archive_template="layouts/archive_template.html"

[tils]
template="layouts/archive_template.html"
filter="templateKey == 'til'"

